config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #


  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true, length: {minimum: 3, maximum: 50} #required variable
  #remember to close de console and start again, to refresh (if you are doing it for the first time)]
  validates :description, presence: true, length: {minimum: 3, maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def index

  end

  def show

    @article = Article.find(params[:id])

  end

  def create

    #store new article in database
    @article = Article.new(article_params)

    if @article.save

      #flash user message
      #       V style             V msg
      flash[:success] = "Article inserted in database"

      #redirect
      redirect_to article_path('new') #go back to new article page
    else
        render 'new' #go again to new article page
    end

  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

    @article = Article.all

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<div class="container">


  <div class="row">
    <div class="col-md-12">

      <h1>Create a new Article</h1>

      <% if @article.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <strong>The following errors occured:</strong>
                <ul>
              <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
                </ul>
              </div>
            <% end %>


      <!--For displaying flash messages-->
      <% flash.each do |style, msg| %>

        <div class="alert alert-<%= style %>" role="alert">
          <%= msg %>

        </div>
      <% end %>


      <%= form_for @article, :url => {:action => "create"} do |f| %>

        <div class="form-group">
          <label for="">Title</label>
          <input type="text"
                 class="form-control" name="article[title]" id="" aria-describedby="helpId" placeholder="">
          <small id="helpId" class="form-text text-muted">Please, insert an title</small>
        </div>

        <div class="form-group">
          <label for="">Description</label>
          <textarea class="form-control" name="article[description]" id="" rows="3"></textarea>
        </div>


        <button type="submit" class="btn btn-success">Post Article</button>

      <% end %>


    </div>
  </div>


</div>

app/views/articles/show.html.erb
<div class="container">


  <div class="row">
    <div class="col-md-12">

      <h1><%= @article.title %></h1>

      <% if @article.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>The following errors occured:</strong>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p><%= @article.description %></p>


      <a href="<%= root_path %>" class="btn btn-primary">Back to Home</a>




    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context.
            Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some
            social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="<%= root_path %>" class="navbar-brand d-flex align-items-center">

        <strong>Ruby on Rails</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>


<main>
  <%= yield %>
</main>


<footer>

</footer>
<!--jQuery-->
<script
src="https://code.jquery.com/jquery-3.3.1.slim.js"
integrity="sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA="
crossorigin="anonymous"></script>


<!--SCRIPTS--->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D" crossorigin="anonymous"></script>


</body>
</html>

app/views/welcome/about.html.erb
<div class="container">



    <div class="row">
      <div class="col-md-12">

        <p>Rails is an awesome framework</p>

        <a href="<%= root_path %>" class="btn btn-primary">Back to home</a>


      </div>
    </div>


</div>

app/views/welcome/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <h1>Ruby on Rails Rocks!</h1>
        <br>
        <a href="<%= new_article_path %>" class="btn btn-success">Post a new Article</a>



      </div>
    </div>

  </div>

  <div class="row">


      <div class="col-md-12">


         <% if @article.any? %>

           <% @article.each do |article| %>


             <div class="card">
               <div class="card-body">
                 <h5 class="card-title"><%= article.title %></h5>
                 <p class="card-text"><%= article.description %></p>
                 <a href="<%= article_path article.id %>" class="btn btn-primary">Check this Article</a>
               </div>
             </div>




           <% end %>



         <% end %>







        <!--<%= link_to 'About', about_path %>-->


      </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-md-12">
      <a href="<%= about_path %>" class="btn btn-primary">About Page</a>
    </div>
  </div>



  </div>
</div>